### ISSUE TITLE
[Zero AI Error] [AI-10005] The command 'jinit' could not be found, expected 'icomplex,iform,jperm,jrs,jplugin,jmod'

### ISSUE THREAD

**Issue by gaoyuanzong** [silentbalanceyh/vertx-ai#8]
[Zero AI] Zero AI 代码生成工具  : <专用工具>
[Zero AI] HomePage   : http://www.vertxai.cn
[Zero AI] Github     : https://github.com/silentbalanceyh/vertx-ai.git
[Zero AI] Version    : 0.3.24  「确认您的Node版本 ( >= 18.x ) 支持ES6, ES7.」
[Zero AI] Zero AI 系统启动......
[Zero AI Error] [AI-10005] The command 'jinit' could not be found, expected 'icomplex,iform,jperm,jrs,jplugin,jmod'
[AI-10005] The command 'jinit' could not be found, expected 'icomplex,iform,jperm,jrs,jplugin,jmod'

0.3.24 jinit not be found

**Comment by gaoyuanzong** [comment]
Error: 错误：[AI-10005] The command 'javaInit' could not be found, expected 'icomplex,iform,jperm,jrs,jplugin,jmod'
    at Object.fxError (/Users/Alive/.nvm/versions/node/v18.8.0/lib/node_modules/vertx-ai/src/epic/ai.under.fn.fx.terminal.js:133:19)
    at _validateArgs (/Users/Alive/.nvm/versions/node/v18.8.0/lib/node_modules/vertx-ai/src/epic/ai.economy.impl.fn.execute.js:45:14)
    at Object.executeBody (/Users/Alive/.nvm/versions/node/v18.8.0/lib/node_modules/vertx-ai/src/epic/ai.economy.impl.fn.execute.js:83:9)
    at Object.<anonymous> (/Users/Alive/.nvm/versions/node/v18.8.0/lib/node_modules/vertx-ai/src/aj.js:9:4)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47

Node.js v18.8.0
